/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
  `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `age` INT NOT NULL,
  `email` TEXT NOT NULL,
  `create_time` BIGINT NOT NULL DEFAULT 'CURRENT_TIMESTAMP')
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `email_i`
  ON `user` (`email`);

