ALTER TABLE groupMember
  ADD COLUMN isMuted TINYINT UNSIGNED NOT NULL DEFAULT 0 AFTER groupNickName,
  ADD COLUMN mutedBy VARCHAR(64) NOT NULL DEFAULT '' AFTER isMuted,
  ADD COLUMN mutedAt BIGINT UNSIGNED NOT NULL DEFAULT 0 AFTER mutedBy;
